### ISSUE TITLE
Port to other systems

### ISSUE THREAD

**Issue by achimwagenknecht** [cemrich/zapp#123]
Zapp is great! I'm sure many users would love it to be ported to Kodi, Linux or Windows. (At least I would love this.)

**Comment by rugk** [comment]
Certainly out of scope…:blush:

**Comment by achimwagenknecht** [comment]
OK, do you mean it's not possible or too costly or not reasonable?

**Comment by return42** [comment]
OT here.

**Comment by achimwagenknecht** [comment]
OK, please excuse my ignorance in this case. Where would be an appropriate place to discuss this?

**Comment by cemrich** [comment]
@achimwagenknecht this is the right place to ask for a port of Zapp.

I am the maintainer of this project. As a working mom I have very limited spare time to work on unpaid open source projects, so there will most likely be no ports. However, there are several other projects using the same API like [MediathekView ](https://mediathekview.de/) for Windows, osx, Linux and Kodi or [MediathekViewWeb ](https://mediathekviewweb.de/) for web clients.

If you have any further questions regarding MediathekView, you are welcome to join the [forums](https://forum.mediathekview.de/)!

**Comment by cemrich** [comment]
@rugk and @return42, I would like you to be more friendly, welcoming and helpful when responding to issues on this tracker. @achimwagenknecht has opened his third GitHub issue in this tracker and cannot be expected to know how all this projects are interconnected. If in doubt, please provide links to the [forums ](https://forum.mediathekview.de/), the [MediathekView ](https://mediathekview.de/) website or similar (closed) issues. Explanations of why you think this issue is out of scope or off topic may have helped a lot. Thank you!

**Comment by return42** [comment]
@cemrich you are right  ..  sorry for being unfriendly .. it was one of theses days, where it is better not to comment., my fail .. @achimwagenknecht please take my apologies.

**Comment by rugk** [comment]
Correct. :+1:

**Comment by achimwagenknecht** [comment]
Thank you very much, @cemrich for clarification and hints! @return42 : apologies accepted. :-)
