### ISSUE TITLE
Mediathek broken (no encrypted connection) 

### ISSUE THREAD

**Issue by giwu37** [cemrich/zapp#134]
I can't open the Mediathek anymore. It opens with an error message which is (translated from German) "Your device cannot establish a secure connection to the server. Probably it helps to update your Android system."
This happens on my phone Moto G4 and on my tablet Mediapad T3. Both on Android 7. 
I am a little bit worried that I have not found anything about that here.
Greetings
Sebastian

**Comment by cemrich** [comment]
This is a known behavior on some Android devices. I am by no means a security expert, but it has something to do with the SSL ciphers supported by the device and by the mediathekviewweb server.

Since when is the mediathek functionality broken on your devices? Did it happen after an app upgrade? If so, which upgrade? If not, maybe @bagbag has updated his server which is causing connection issues.

I am using an Android 7.1 device myself during development and the mediathek connection is working just fine - so we triage a bit to reproduce the issue.

**Comment by cemrich** [comment]
@bagbag thank you very much for your quick response! I can reproduce the error (SSLHandshakeException) on an Android 7.0 device (api level 24). There is [a known bug](https://stackoverflow.com/questions/39133437/sslhandshakeexception-handshake-failed-on-android-n-7-0) in this Android version regarding SSL ciphers.

@giwu37 if possible I would recommend to update your devices as this is a security issue. Zapp already supports older TLS versions (see https://github.com/cemrich/zapp/blob/master/app/src/main/java/de/christinecoenen/code/zapp/app/mediathek/ui/list/MediathekListFragment.java#L91). But as I am no crypto expert by any means, I would like to avoid tampering with the SSL connection any further on the apps side.

**Comment by bagbag** [comment]
The workaround for that bug to enable `prime256v1` ([also named `secp256r1` and `NIST P-256`](http://www.rfc-editor.org/rfc/rfc4492.txt)) at my side, would lead to an vulnerable encryption, according to [safecurves.cr.yp.to](https://safecurves.cr.yp.to/). Because of this I won't do that.

So your only solution seems to be upgrading your android version.

**Comment by rugk** [comment]
BTW, @bagbag, what server are you even maintaning that Zapp includes?

**Comment by bagbag** [comment]
@rugk, the Mediathek feature of Zapp uses the API of mediathekviewweb.de, which is my website and therefore runs on my servers.

**Comment by giwu37** [comment]
> **I've enabled it.**

That worked. I can only test on my mobile now but there it works again. Thanks!

**Comment by bagbag** [comment]
I'm glad I could help :)

**Comment by cemrich** [comment]
@bagbag Thank you very much for your help!
