### ISSUE TITLE
Support for Android TV

### ISSUE THREAD

**Issue by cemrich** [cemrich/zapp#59]

**Comment by upost** [comment]
Hi!
I see that this is closed, but actually Android TV support is not complete because channel/program icons are not shown on the Android TV main screen (leanback launcher).
I forked the code and added this feature. Please have a look and feel free to merge it:
https://github.com/upost/zapp/commit/0d0691d9891816f9173ed42439261deaacaa2248
See Screenshot (from Emulator):
![Zapp on Android TV](https://user-images.githubusercontent.com/6184056/86405539-d52dc000-bcb1-11ea-90f1-fc9bb61430a4.jpg)

**Comment by rugk** [comment]
@upost I'd suggest you to create a PR then. This is what PRs are for…

**Comment by upost** [comment]
Yes of course, but it might not be desired to have that feature anyway because this issue was closed ... and the solution has some disadvantages, so someone might want to look into it beforehand ...

**Comment by return42** [comment]
> and the solution has some disadvantages, 

If you send a PR the pros & cons can be discussed with remarks along the patch.

**Comment by cemrich** [comment]
Thank you @upost ! I'll look into it as soon as I have a view minutes oft spare time (which may take a while, sorry).

**Comment by cemrich** [comment]
@upost I created the pull request #191 and will discuss further changes there.
